application: timeintab
version: 9
runtime: python
api_version: 1

default_expiration: "1s"

handlers:

- url: /
  static_files: sf/index.html
  upload: sf/index.html

- url: /privacy
  static_files: sf/privacy.html
  upload: sf/privacy.html

- url: /sf/main.appcache
  static_files: sf/main.appcache
  mime_type: text/cache-manifest
  upload: sf/main.appcache

- url: /sf/clocktab.webapp
  static_files: sf/clocktab.webapp
  mime_type: application/x-web-app-manifest+json
  upload: sf/clocktab.webapp

- url: /sf
  static_dir: sf
